/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vector;

import java.util.Iterator;

import java.util.concurrent.atomic.AtomicReference;



import com.vector.model.CatFact;
import com.vector.model.Dog;
import com.vector.services.APIService;
import com.vector.services.APIServiceImpl;

import discord4j.core.DiscordClient;
import discord4j.core.event.domain.channel.TypingStartEvent;

import discord4j.core.event.domain.lifecycle.ReadyEvent;
import discord4j.core.event.domain.message.MessageCreateEvent;

import discord4j.core.object.entity.Message;
import discord4j.core.object.entity.User;
import discord4j.gateway.intent.Intent;
import discord4j.gateway.intent.IntentSet;
import reactor.core.publisher.Mono;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static Logger logger = LoggerFactory.getLogger(App.class);
    private static APIService apiService = new APIServiceImpl();
    public static void main(String[] args) {
        DiscordClient client = DiscordClient.create(args[0]);
        logger.info("Hello");
        Mono<Void> login = client.withGateway(gateway->
            gateway.on(ReadyEvent.class,event->
                Mono.fromRunnable(()->{
                    final User self = event.getSelf();
                    System.out.println(String.format("Logged in as %s#%s%n",self.getUsername(),self.getDiscriminator()));
                    Iterator<Intent> set = IntentSet.all().iterator();
                    while(set.hasNext()){
                        System.out.println(set.next());
                    }
                })
            ).then().and(gateway.on(MessageCreateEvent.class,event -> {
                Message message = event.getMessage();

                if(message.getContent().equalsIgnoreCase("!ping")){
                    return message.getChannel().flatMap(channel->channel.createMessage("pong!"));
                } else if(message.getContent().equalsIgnoreCase("!catfact")) {
                    System.out.println("Inside catfact");
                    AtomicReference<CatFact> fact = new AtomicReference<>();

                    
                    fact.set(apiService.getAPIResponse(CatFact.class,"https://catfact.ninja/fact"));
                    return message.getChannel().flatMap(channel->channel.createMessage(fact.get().getFact()));
                 } else if(message.getContent().equalsIgnoreCase("!dogimage")){

                     return message.getChannel().flatMap(channel->channel.createMessage(apiService.getAPIResponse(Dog.class, "https://dog.ceo/api/breeds/image/random").getMessage()));
                    
                 }
                return Mono.empty();
            }).then().and(gateway.on(TypingStartEvent.class,event->{
                return Mono.fromRunnable(()->{
                    logger.info("Me inside TypingStartEvent");
                    System.out.printf("%s#%s started typing%n",event.getUser().blockOptional().get().getUsername(),event.getUser().blockOptional().get().getDiscriminator());
                }); 
                
            })).then())
        );
        login.block();
    }
}
